### ISSUE TITLE
Download data does not represent file name correctly

### ISSUE THREAD

**Issue by UnidentifiedX** [Bluegrams/YoutubeDLSharp#19]
I think this doesn't work for non-ASCII characters. Take racing into the night (夜に駆ける), for example. While it does save the file name correctly, taking RunResult.Data returns a file path of `C:\...\bin\Debug\net6.0-windows\output\.mp3`. As you can see, I can no longer get the file path of the audio file.
![image_2022-10-24_110445459](https://user-images.githubusercontent.com/80146445/197440594-7b7fcd46-d51f-49d6-a307-77fe5030df0d.png)

**Comment by alxnull** [comment]
Thanks for bringing up this issue. After some investigation, I implemented a fix for this in https://github.com/Bluegrams/YoutubeDLSharp/commit/fdf3256da18d0e2da4a2f33ad4a1b72ff8273a50. The fix should be available with the next release.
