### ISSUE TITLE
bytestream?

### ISSUE THREAD

**Issue by TybaIt** [Bluegrams/YoutubeDLSharp#2]
I want to play a video while it's still downloading.

I've tried it using the YoutubeDLProcess (params: NoPart) and the OutputReceivedEvent. This just gives me the current state of the downloader.

In my case I want to use just the audiotrack. Conviniently I would like to use ``_youtubeDL.RunAudioDownload(url, YoutubeDLSharp.Options.AudioConversionFormat.Mp3)``
and start it once its progress is above like 3% using CSCore

**Comment by alxnull** [comment]
Hi,

Currently, there's no convenient built-in way to obtain a bytestream. The downloading methods of the `YoutubeDL` class such as `RunAudioDownload()` use youtube-dl's mechanism of downloading the video to the file system and then performing post-processing using ffmpeg, so they're not directly usable.

In principal, it should be possible to write the download stream to the output using `options.Output = "-"` and then processing this output. However, the most flexible way probably is to only extract the url of the video/ audio stream using youtube-dl and then streaming from this url using a different tool such as ffmpeg, NAudio, CSCore. E.g., based on [a sample from NAudio](https://github.com/naudio/NAudio/blob/master/Docs/PlayAudioFromUrl.md):

```csharp
// fetch audio stream url
YoutubeDL ytdl = new YoutubeDL();
var options = new OptionSet() { Format="m4a", GetUrl=true };
string streamUrl = ytdl.RunWithOptions(
    new[] { videoUrl },
    options,
    CancellationToken.None
).Result.Data[0];
// play audio from url
using (var mf = new MediaFoundationReader(streamUrl))
using (var wo = new WaveOutEvent())
{
    wo.Init(mf);
    wo.Play();
    while (wo.PlaybackState == PlaybackState.Playing)
    {
        Thread.Sleep(1000);
    }
}
```
