### ISSUE TITLE
Exception for paths with spaces

### ISSUE THREAD

**Issue by albie6544** [Bluegrams/YoutubeDLSharp#28]
I am currently using version 1.0.0.beta3 with yt-dlp and have encountered an error that had baffled me for a good while. When creating a new youtubedl object, my path had a space in it (C:\Project Repo\Project\asdf\yt-dlp.exe), causing an error. Hope this can get fixed soon, thanks ;)

**Comment by alxnull** [comment]
Thanks for reporting this. I've just fixed the issue and pushed an updated nuget package including this fix.
