### ISSUE TITLE
filename options

### ISSUE THREAD

**Issue by hswlab** [Bluegrams/YoutubeDLSharp#36]
I noticed that sometimes the file name is not generated correctly. In this case I get file names that look like the following example "index-v1-a1 [index-v1-a1].mp4". The title is actually determined correctly in the fetch result, only when creating the filename there sometimes seems to be problems. Is there a way to configure a custom title for the filename? Actually I would like to have a filename like in this example.

```
string videoTitle = "This is a video title without special characters";
string videoQuality = "720p";
string myFileName = $"{videoTitle} [{videoQuality}].%(ext)s"
```

**Comment by TooLoose** [comment]
ytdl.OutputFileTemplate= "D:\\AVI\\Jones-%(title)s.%(ext)s"

**Comment by alxnull** [comment]
In addition to the answer already given, file names can be specified on a per-download basis as described here: https://github.com/Bluegrams/YoutubeDLSharp/issues/40#issuecomment-1872540894
