### ISSUE TITLE
Can this library be used for a .Net MAUI Android project?

### ISSUE THREAD

**Issue by CDrosos** [Bluegrams/YoutubeDLSharp#38]
Sorry for the question but im not sure if i can use it in a MAUI project

**Comment by alxnull** [comment]
Hey, the library is built to target both .NET Standard 2.0 and .NET 6+, so you should be able to add it to MAUI projects. The main limitation comes from yt-dlp as the platform you deploy to must support running yt-dlp binaries. See here for more: https://github.com/yt-dlp/yt-dlp/wiki/Installation.
