### ISSUE TITLE
FlatPlaylist Option does not work with RunAudioPlaylistDownload/RunVideoPlaylistDownload

### ISSUE THREAD

**Issue by darkphyre** [Bluegrams/YoutubeDLSharp#39]
I might not be using the library the correct way, so I admit this might not be a problem, but what I want to do is essentially list all the videos/audio in a playlist and just return the urls.  The reason for this is because several of the watchlists I want to download have overlapping videos and it seems to be redundant.  When I try the code below with the FlatPlaylist option all that happens is an empty[].   Maybe I'm not using the library correctly?

```
// See https://aka.ms/new-console-template for more information
using YoutubeDLSharp;
using YoutubeDLSharp.Metadata;
using YoutubeDLSharp.Options;

string basePath = System.AppDomain.CurrentDomain.BaseDirectory;
var ytdl = new YoutubeDL();
ytdl.YoutubeDLPath = Path.Combine($"{basePath}yt-dlp.exe");
ytdl.FFmpegPath = Path.Combine($"{basePath}ffmpeg.exe");
ytdl.OutputFolder = @"H:\Youtube\Test";
var optionsSet = new OptionSet()
{
    FlatPlaylist = true
};
string vid_target = "mywatchlist";
string[] vid_targets = new string[] { vid_target };

var ytdlProc = new YoutubeDLProcess();
var proc = await ytdlProc.RunAsync(vid_targets, optionsSet);
var res = await ytdl.RunAudioPlaylistDownload(vid_target, 1, 100, null, AudioConversionFormat.Mp3, default, null, null, optionsSet);
Console.ReadLine();
```

![image](https://github.com/Bluegrams/YoutubeDLSharp/assets/13712206/28623a35-7466-42fd-b4a7-71e4db47f6c0)

**Comment by alxnull** [comment]
Hey @darkphyre, this behaviour is expected. Passing `FlatPlaylist = true` will prevent any playlist items to be extracted, therefore no videos will be downloaded.

I'm not completely sure what you're trying to achieve, but from my understanding, the goal is to retrieve urls for all playlist items. You can achieve this via `RunVideoDataFetch()`, e.g. like this:

```csharp
// flat: false will make sure playlist items are extracted
var res = await ytdl.RunVideoDataFetch(vid_target, flat: false);
// Get web url of each playlist item
var playlistUrls = res.Data.Entries.Select(e => e.WebpageUrl).ToArray();
```
