### ISSUE TITLE
Support custom arguments

### ISSUE THREAD

**Issue by TheMulti0** [Bluegrams/YoutubeDLSharp#4]
Hi there! I've been using this library and I'm very pleased.

However I have recently started using [yt-dlp](https://github.com/yt-dlp/yt-dlp) instead of youtube-dl (by just giving this library the path to yt-dlp instead of youtube-dl binary), and given this fork has arguments not supported in youtube-dl I would love to have the option to pass custom string arguments.

Thanks!

**Comment by alxnull** [comment]
Hi @TheMulti0, this makes a lot of sense, will try to implement it.
Maybe it also makes sense to support yt-dlp directly in the longer term as this seems to be the much more active project.

**Comment by TheMulti0** [comment]
> Hi @TheMulti0, this makes a lot of sense, will try to implement it.
> Maybe it also makes sense to support yt-dlp directly in the longer term as this seems to be the much more active project.

Yo, I'd love if you will add the hacktoberfest topic to the repo and then I'll implement that feature :)
