### ISSUE TITLE
Ability to set the filename of the video to be downloaded

### ISSUE THREAD

**Issue by lecoding111** [Bluegrams/YoutubeDLSharp#40]
I wanna know if it's possible to set the download name of the file to be download using RunVideoDownload() or RunAudioDownload()

**Comment by alxnull** [comment]
Hey, you can use the `Output` option to specify custom download file names for each call of RunVideoDownload() or RunAudioDownload(), e.g.:

```csharp
var ytdl = new YoutubeDL();
var options = new OptionSet() { Output = "<YOUR_OUTPUT_TEMPLATE>" };
var result = ytdl.RunVideoDownload(url, overrideOptions: options);
```

You may use specify all output templates supported by yt-dlp/ youtube-dl here: https://github.com/yt-dlp/yt-dlp#output-template
