### ISSUE TITLE
Nullable Enums are set to default(T) instead of null when their value is null

### ISSUE THREAD

**Issue by gmihovics** [Bluegrams/YoutubeDLSharp#47]
I noticed when looking at the `VideoData` for a deserialised playlist, the availability of each entry was listed as `Private`. I knew they were public videos and I checked the raw output from yt-dlp and it was returning `null`. It seems even though `Availability` is specified as nullable in `VideoData`, the `StringToEnumConverter` that deserializes it returns `default(T)` when the value is `null`. I would think if the enum is nullable, null should be returned instead.

**Comment by alxnull** [comment]
Thanks for reporting! This has been fixed and will be part of the next package release.
