### ISSUE TITLE
How to use Paths

### ISSUE THREAD

**Issue by destrugter** [Bluegrams/YoutubeDLSharp#49]
I'm trying to figure out how to use Paths. From an example I saw for the CLI you can do `-P "home:final/path" -P "temp:ssd/path" -o "file-name.%(ext)s"`. When I try this with the Paths property, I can only set it once not multiple times which is leading to my confusion on how to use it, or if it was forgotten to include multiple values?

**Comment by alxnull** [comment]
This was indeed incorrect in the implementation. Now changed `Paths` to allow multiple values as described here: https://github.com/Bluegrams/YoutubeDLSharp?tab=readme-ov-file#working-with-options
