### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by DubyaDude** [Bluegrams/YoutubeDLSharp#52]
I'm currently using this in a project of mine, we ran into the bug fixed by https://github.com/Bluegrams/YoutubeDLSharp/commit/e16e2ce49dd13bf5181bfdbc401a2617c4fa6389. We've worked around it by using git submodules, but would greatly appreciate a NuGet package update whenever you're free as it'd be preferred.

Thanks a ton for this project otherwise, it's been super helpful!

**Comment by alxnull** [comment]
Pushed a new package to NuGet, thanks for reminding!
