### ISSUE TITLE
How I can use this repo to do the job yt-dlp can do?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Bluegrams/YoutubeDLSharp#6]
Hello:
I found one web site, which I can see live sports video, and using the tool yt-dlp, I can download the underlying m3u8 link.
One example is something like:

yt-dlp https://m3u8.1proxy.xyz/media/g_18/playlist.m3u8 --downloader ffmpeg --referer "https://bingsport.com/"

You can find some live streams from the following URL: 
(# can be a number from 1 to 20 or 30 depend on how many live games have for today).
https://bingsport.com/1proxy.php?id=g_#

Let me know if I can do the job like yt-dlp does with this repo with some type of custom arguments?  As I need API library in C# for my project.
Thanks,

**Comment by alxnull** [comment]
Hey @zydjohnHotmail, sorry for the late answer.

This library can be used with yt-dlp and you can also pass arguments custom to yt-dlp, e.g. like this:

```csharp
YoutubeDL ytdl = new YoutubeDL();
ytdl.YoutubeDLPath = "yt-dlp.exe";
// parse custom options from string
var options = OptionSet.FromString(new[] {
    "--downloader ffmpeg",
    "--referer https://bingsport.com/"
});
await ytdl.RunVideoDownload("https://m3u8.1proxy.xyz/media/g_18/playlist.m3u8", overrideOptions: options);
```

Hope this helps
