### ISSUE TITLE
All methods never complete

### ISSUE THREAD

**Issue by ReadieFur** [Bluegrams/YoutubeDLSharp#9]
I am using .NetCore 6.0. When I try to run any operation wether that be RunVideoFetch or RunVideoDownload etc, nothing ever happens. If I pass in a function for the progress callback, I always remain at 0%. What I find more odd about this is the WPF demo does work and I have tried replicating that too but no luck.
```cs
YoutubeDL ytdl = new YoutubeDL();
ytdl.YoutubeDLPath = ytdlPath; //Both paths are valid, no error.
ytdl.FFmpegPath = ffmpegPath;
await ytdl.RunVideoDownload(
    $"https://www.youtube.com/watch?v={videoID}",
    progress: new Progress<DownloadProgress>(downloadProgress => Console.Write($"\r{downloadProgress.Progress * 100}%"))
);
//Never completes, no errors.
```
I am truly confused here as to why this isn't working.

**Comment by alxnull** [comment]
Hey @ReadieFur, unfortunately, I wasn't able to reproduce this issue on my side, so I'm not sure what the cause for this may be. I added .NET 6 as target in the WPF demo app (https://github.com/Bluegrams/YoutubeDLSharp/commit/c3f16255fc37463f9da947ee54cbdd2e94b61917) and it seems to work there.

**Comment by ReadieFur** [comment]
Yeah it was an odd one, not sure what caused it but I ended up just making my own basic wrapper for YT-DLP only covering the features I needed to use.
